# Generated by Django 3.2.5 on 2022-07-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_auto_20220701_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
